# Generated by Django 4.0.4 on 2022-06-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NflWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtsWeek',
            fields=[
                ('id_pts_week', models.IntegerField(primary_key=True, serialize=False)),
                ('broj_bodova', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PTS_week',
                'managed': False,
            },
        ),
    ]
