# Generated by Django 4.0.4 on 2022-06-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NflWeb', '0002_ptsweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OkladaKolo',
        ),
    ]
