# Generated by Django 4.0.4 on 2022-07-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NflWeb', '0003_delete_okladakolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkladaKolo',
            fields=[
                ('id_oklada_kolo', models.AutoField(primary_key=True, serialize=False)),
                ('broj_td', models.IntegerField(blank=True, db_column='broj_TD', null=True)),
            ],
            options={
                'db_table': 'Oklada_kolo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Oklada',
        ),
    ]
